/*Hand in this file ONLY!*/
/*Hand in this file ONLY!*/
/*Hand in this file ONLY!*/

void* A51Initial(unsigned long long sessionKey,unsigned int frameCounter){
/* Using this funciton to initialize your A5-1 stream cipher state.
 * sessionKey: a 64-bit unsigned integer
 *             This should be used from LSB to MSB
 *   Ex. sessionKey = 0x000000000000000b = 0b0000...00001011
 *       Then, it will be translate to "1101 0000 ... 0000" in the video
 * frameCounter: a 22-bit unsigned integer
 *               This should be used from LSB to MSB, the same as sessionKey
 * This funtion returns a structure defined by yourself to keep the 
 * stream cipher state
 */

/*Your code...*/
 
}
 
unsigned char A51GetByte(void* LFSR){
/* Using this function to get a 8-bit key stream from the current state
 * LFSR: the current A5-1 stream cipher state
 * This function returns an unsigned char which generated by your A5-1
 *      The 8-bit key stream is generated from MSB to LSB
 *   Ex. The generated 8-bit key stream = 0 1 0 0 1 1 0 1
 *       Then, the returned unsigned char is 0x4d = 77
 */

/*Your code...*/
 
}
